### ISSUE TITLE
Slow horizontal scrolling

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-osx#1]
I finally had a chance to try the OSX package, it works great so far!

One little issue I noticed, which is probably due to Scintilla's buggy horizontal scrolling is that when you scroll horizontally, it's really really slow. The vertical scrolling is nice and smooth and fast.

OSX 10.9.5, Geany from the nightly linked in the geany-osx/README.md file.

**Comment by techee** [comment]
Great, thanks for trying it!

Yep, horizontal scrolling is a bit slow. The most annoying thing with horizontal scrolling at least for me is that it happens when scrolling using the touchpad and when the gesture isn't completely vertical. In gtk 2 the horizontal/vertical scroll events are delivered separately so it's not possible to ignore small horizontal scroll when there's a big vertical one (Apple seems to do this for widgets with both horizontal/vertical scrollbars which is a good idea IMO).

It should be possible with gtk 3 (together with smooth scrolling) but first scintilla doesn't use the new events and second I found gtk 3 a bit too buggy (especially with retina displays) so I until it's fixed, I don't plan providing a gtk3-based bundle.

If you don't have a retina display, you may speed up things a little (but really just a little) by removing the ifdef here

https://github.com/geany/geany/blob/master/src/editor.c#L4783

With gtk2 I didn't find a way to do this automatically (since cairo 1.14 and I think gtk 3.12 there's a support of hidpi displays and the bitmap backend used by scintilla works fine, doubling the resolution automatically).

**Comment by codebrainz** [comment]
On 2015-04-04 9:35 AM, Jiří Techet wrote:

> Yep, horizontal scrolling is a bit slow. The most annoying thing with
> horizontal scrolling at least for me is that it happens when
> scrolling using the touchpad and when the gesture isn't completely
> vertical. In gtk 2 the horizontal/vertical scroll events are
> delivered separately so it's not possible to ignore small horizontal
> scroll when there's a big vertical one (Apple seems to do this for
> widgets with both horizontal/vertical scrollbars which is a good idea
> IMO).

I agree that is kind of weird how when you scroll up/down it goes 
sideways too.

**Comment by techee** [comment]
I think this isn't an issue any more with the latest GTK drawing improvements on macOS. Closing.
