### ISSUE TITLE
VTE doesn't respect/use PS1 environment variable

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-osx#3]
When I start Geany the default prompt in VTE is `sh-3.2$` rather than using the `PS1` variable that Terminal.app and such use. It uses it on Linux, so maybe something with the bundle makes it not inherit/access exported environment variables?

Once the variable is changed to something more normal it does use it.

**Comment by techee** [comment]
I think UI applications on OS X are started using launchd and not through terminal so the environment variable isn't defined.

And I don't think Terminal.app reads PS1 either - I think it just runs bash as a login shell and bash reads the corresponding config file from which it gets PS1.

For Geany we have 2 options:
1. Start bash as login shell so the shell command is '/bin/bash -l'
2. In the wrapper script add export PS1='some reasonable value'

Both of these options work. I would go for (1) unless there's some problem with it. What do you think?

**Comment by codebrainz** [comment]
I'm not really sure what is the repercussions of (1).

**Comment by elextr** [comment]
On 6 April 2015 at 09:53, Matthew Brush notifications@github.com wrote:

> I'm not really sure what is the repercussions of (1).

​We wouldn't want to do that on Linux because it would then overwrite any
variables set on the command line before Geany is run.​

**Comment by pwil3058** [comment]
I'm seeing a related problem in the VTE with bash in the Geany terminal.  It seems to be trying to honour my PS1 setting but is adding a lot of other rubbish as well.  I have PS1 set to "\w \$" which should give me:

~/SRC/GITHUB/gwsmgitd $

 but I get: 

]777;notify;Command completed;./gwsmgitd]7;file://mudlark.localdomain/home/peter/SRC/GITHUB/gwsmgitd~/SRC/GITHUB/gwsmgitd $

instead.  I don't know whether it's a bash problem or a Geany problem but I do not get this problem in my own PyGObject scripts that use Vte version 2.91.

It's a bit annoying as it takes up most of the line and also seems to interfere with line editing at times.

**Comment by techee** [comment]
Where do you set PS1? Normally Mac terminal runs bash as a login shell (which Geany does now too by defaulting to "bash -l" to grab the system settings of PS1) so you have to set PS1 inside .bash_profile (.bashrc won't be used). For me using

```
PS1="\w \$"
```

inside .bash_profile works as expected. Also check that you have "bash -l" inside Editor->Preferences->Terminal->Shell. If you have just "bash" there then bash isn't run as a login shell and you have to set PS1 inside .bashrc. What does "echo $PS1" say when you run it inside Geany's VTE? I guess it's something different than "\w \$".

**Comment by pwil3058** [comment]
Adding the -l to Editor->Preferences->Terminal->Shell seems to have fixed the problem.  Thanks.

**Comment by pwil3058** [comment]
I spoke too soon.  I'm still seeing this problem but only under very peculiar circumstances in that it only happens if I launch geany from a Python script using:

subprocess.Popen(["geany", "-i"])

(also without the "-i") but (and here's the weird part) only if the Python code is being executed from within a GNOME Terminal or from within a program that was started from inside a GNOME Terminal.
Just made another test and it also happens if I launch geany directly from the command line in a GNOME Terminal. (The version I have installed is GNOME TERMINAL 3.20.2 and it may not be the case for other versions.)

If I start geany from the menu or using Python inside a program launched from the menu (or from a program launched from geany's terminal) I don't see the problem.

So it seems that there's some sort of weird interaction between geany and GNOME Terminal but I'm not sure if it's worth pursuing this issue any further.

**Comment by codebrainz** [comment]
@pwil3058 as a Python-specific workaround, you might do something like (untested):

``` python
import os
env = dict(os.environ)
env["PS1"] = "\\w \\$"
# or something like:
# env["PS1"] = env.get("PS1", "\\w \\$")
subprocess.Popen(["geany", "-i"], env=env)
```

**Comment by pwil3058** [comment]
I thought about twiddling the environment inside my programs as you suggest but discounted it after I discovered that I got the same problem with geany's terminal if I launched geany directly from the command line inside the GNOME Terminal as this indicated that Python probably (if not definitely) wasn't implicated.

I'm going to avoid the problem by not using GNOME Terminal anymore. I mainly only use it when I'm testing my GUIs and need to be able to see any gumph that Gtk spits out to standard error or Python exceptions that I've failed to catch.  Even though it might be wasteful of resources using geany for just its terminal I can use the terminal of a geany instance to achieve this end.

I also might write a 20 (or so, excluding the GPL copyright notice) line Python/PyGObject script that would provide a program with the essential functionality of GNOME Terminal without all the frills.

**Comment by elextr** [comment]
> I also might write a 20 (or so, excluding the GPL copyright notice) Python/PyGObject script that would provide a program with the essential functionality of GNOME Terminal without all the frills.

Or just install xterm from the repo.

**Comment by pwil3058** [comment]
That works but might be too minimal for me in that the text is very small and there's no way to change it.

Although, 20 lines might be optimistic for the script as inspection of my current wrapper code for Vte
(which just puts it in a scrolled window and gives cut/paste functionality)  is about 60 lines.

**Comment by codebrainz** [comment]
`xfce4-terminal` is a gtk/vte based terminal like gnome-terminal, another option (among many).

**Comment by pwil3058** [comment]
xfce4-terminal and mateterminal have the same problem as GNOME terminal.

Ones I've tried (inspired by your suggestion) that don't have the problem are lxterminal, xterm, roxterm and termit.  I didn't try any Qt based ones.

I'm going to go out on a limb and suggest the difference might be GTK 2 based systems have the problem and GTK 3 based ones don't.

I think I'll scrap the idea of writing my own and go with lxterminal as it certainly seems that the last thing the world needs is another terminal emulator.

**Comment by voleary** [comment]
Hoping this helps someone: I had a similar issue where I was getting a bunch of garbage in front of my terminal prompt in Geany. 

Found this solution on stack overflow for the same issue but using pycharm : https://stackoverflow.com/questions/41205437/set-up-path-on-prompt-on-pycharm-terminal-windon
Since I also have iterm2 installed on my Macosx, I believe this was causing the issue.

How I resolved in Geany Terminal:

1. I created & saved a file  **geany_terminal.sh**  and saved it in my home folder. copied my desired PS1 and CLICOLOR settings from my .bash_profile: 

```
#~/geany_terminal.sh
export PROMT_COMMAND=
export PS1='\[\e[1;32m\][\u@\h \W] \D{%F %T}\n\$\[\e[0m\]'
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
bash -i
```

2. Then I went to 'Edit -> Preferences --> Terminal' and set my 'Shell' to:
/bin/bash /Users/myusername/geany_terminal.sh

Upon reloading Geany, the Terminal now displays with PS1 and CLICOLOR settings exactly as I have set in my .bash_profile without garbage in front.
